create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

alter table push_subscriptions enable row level security;

create policy "Users can manage their own push subscriptions"
on push_subscriptions for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
